# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class DockerCredentialEcrLoginWithEnv < Formula
  desc "Wrapper command for docker-credential-ecr-login to add environment variables."
  homepage "https://github.com/winebarrel/docker-credential-ecr-login-with-env"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/winebarrel/docker-credential-ecr-login-with-env/releases/download/v0.1.0/docker-credential-ecr-login-with-env_0.1.0_darwin_amd64.tar.gz"
      sha256 "a961a6efe333555691c49df8aca06470fbe0c987a3632e476aeca87e347606df"

      def install
        bin.install 'docker-credential-ecr-login-with-env'
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/winebarrel/docker-credential-ecr-login-with-env/releases/download/v0.1.0/docker-credential-ecr-login-with-env_0.1.0_darwin_arm64.tar.gz"
      sha256 "3999d3022436f9266a0adde9b2f9714fc0c7b87e2776313663501c11c8b8420f"

      def install
        bin.install 'docker-credential-ecr-login-with-env'
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/winebarrel/docker-credential-ecr-login-with-env/releases/download/v0.1.0/docker-credential-ecr-login-with-env_0.1.0_linux_arm64.tar.gz"
      sha256 "668d0da3d381716b7fdb9bba26f7ddb1970c7f4e4527a678d3f25aedbfa7b85c"

      def install
        bin.install 'docker-credential-ecr-login-with-env'
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/winebarrel/docker-credential-ecr-login-with-env/releases/download/v0.1.0/docker-credential-ecr-login-with-env_0.1.0_linux_amd64.tar.gz"
      sha256 "26c15afbad700040daad8fae478aadc9bf3199c63b394422a5bf5450be975ced"

      def install
        bin.install 'docker-credential-ecr-login-with-env'
      end
    end
  end
end
