# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class DockerCredentialEcrLoginEnv < Formula
  desc "Wrapper command for docker-credential-ecr-login to add environment variables."
  homepage "https://github.com/winebarrel/docker-credential-ecr-login-env"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/winebarrel/docker-credential-ecr-login-env/releases/download/v0.2.0/docker-credential-ecr-login-env_0.2.0_darwin_amd64.tar.gz"
      sha256 "c12a74d71698aa4d0701a1838baec2ef1af26b87cb123c710d051cf418b1d6be"

      def install
        bin.install 'docker-credential-ecr-login-env'
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/winebarrel/docker-credential-ecr-login-env/releases/download/v0.2.0/docker-credential-ecr-login-env_0.2.0_darwin_arm64.tar.gz"
      sha256 "46f2fa48c0337d40537242fabd10f433bc33f0e9e386d93c9e2d8542a93ec055"

      def install
        bin.install 'docker-credential-ecr-login-env'
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/winebarrel/docker-credential-ecr-login-env/releases/download/v0.2.0/docker-credential-ecr-login-env_0.2.0_linux_arm64.tar.gz"
      sha256 "0f6621226807b6ba07d3ddac94277c5e71e463c083140de15de964af938b56a3"

      def install
        bin.install 'docker-credential-ecr-login-env'
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/winebarrel/docker-credential-ecr-login-env/releases/download/v0.2.0/docker-credential-ecr-login-env_0.2.0_linux_amd64.tar.gz"
      sha256 "bedb075653ae4854dc14148685e67c44f03554ce6382f9323afeef2712710f41"

      def install
        bin.install 'docker-credential-ecr-login-env'
      end
    end
  end
end
